###
# File: .drone.yml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Monday, March 9th 2020, 5:11:52 pm
# Last Modified: Monday, June 8th 2020, 11:03:05 am
#
# http://www.opensource.org/licenses/MIT
###

kind: pipeline
type: docker
name: build_and_run_on_docker

steps:
  - name: build
    image: golang:1.16
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - make clean test build
      - ./target/obsync -v

trigger:
  branch:
    - develop

#---
#kind: pipeline
#type: exec
#name: build_and_publish_docker_images
#branch: master
#
#platform:
#  os: linux
#
#steps:
#  - name: env
#    commands:
#      - uname -a && docker info
#  - name: build
#    environment:
#      GOPROXY: https://goproxy.cn
#      GOOS: linux
#      DOCKER_REPO_NAME: mingcheng/obsync
#      DOCKER_REPO_HOST: swr.la-south-2.myhuaweicloud.com
#      DOCKER_PASSWD:
#        from_secret: docker_password
#      DOCKER_USER:
#        from_secret: docker_username
#    commands:
#      - make docker_image_publish
#trigger:
#  branch:
#    - master
