###
# File: .drone.yml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Monday, March 9th 2020, 5:11:52 pm
# Last Modified: Monday, June 8th 2020, 11:03:05 am
#
# http://www.opensource.org/licenses/MIT
###

kind: pipeline
type: docker
name: build_and_run_on_docker

steps:
  - name: build
    image: golang:1.16
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - make clean test build
      - ./target/obsync -v

  - name: publish-image
    image: plugins/docker
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    environment:
      GOPROXY: "https://goproxy.cn,direct"
    when:
      branch:
        - master
      event:
        - push
    settings:
      registry: ghcr.io
      repo: ghcr.io/mingcheng/obsync
      username: mingcheng
      password:
        from_secret: cr_pat
      dockerfile: Dockerfile
      custom_dns: 119.29.29.29
      tags:
        - latest
        - 1.2.0

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
