###
# File: .drone.yml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Monday, March 9th 2020, 5:11:52 pm
# Last Modified: Sunday, May 24th 2020, 10:11:26 pm
#
# http://www.opensource.org/licenses/MIT
###

kind: pipeline
type: docker
name: build_and_run_on_docker

steps:
  - name: build
    image: golang:1.13.11
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - make clean build
      - ./target/obsync -v
trigger:
  branch:
    - develop

---
kind: pipeline
type: exec
name: build_and_publish_docker_images

platform:
  os: linux
steps:
  - name: build
    environment:
      GOPROXY: https://goproxy.cn
      GOOS: linux
      DOCKER_REPO_NAME: mingcheng/obsync
      DOCKER_PASSWD:
        from_secret: docker_password
      DOCKER_USER:
        from_secret: docker_username
      DOCKER_REPO_HOST:
        from_secret: docker_repo_host
    commands:
      - env
      - make docker_image_publish
trigger:
  branch:
    - master
