include:
  - project: "segmentfault/devops/templates"
    file: ".docker-build-push.yml"
  - project: "segmentfault/devops/templates"
    file: ".deploy-helm.yml"

stages:
  - compile
  - push

"compile the golang project":
  image: golang:1.19
  stage: compile
  script:
    - make clean build
  before_script:
    - export GOPROXY="https://goproxy.cn"
  artifacts:
    paths:
      - obsync

"build docker images and push to repository":
  stage: push
  extends: .docker-build-push
  only:
    - master
  variables:
    DockerNamespace: sf_util
    DockerImage: obsync
    DockerTag: "1.5.0 latest"
    DockerfilePath: .
    PushPolicy: qingcloud
