name: Publish to Huawei Cloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Huawei Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Build the Docker image and Publish to Huawei Cloud
        run: make docker_image_publish
        env:
          DOCKER_REPO_NAME: mingcheng/obsync
          DOCKER_REPO_HOST: swr.la-south-2.myhuaweicloud.com
          DOCKER_PASSWD: ${{ secrets.docker_password }}
          DOCKER_USER: ${{ secrets.docker_username }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: mingcheng/obsync/obsync
          tag_with_ref: true
